server:
  port: 7700
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: diary
          uri: lb://diary
          predicates:
            - Path=/diary/**
